# Generated by Django 2.0.5 on 2018-05-19 13:50

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('intro', tinymce.models.HTMLField()),
                ('post', tinymce.models.HTMLField()),
                ('img_url', models.URLField(blank=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
